### ISSUE TITLE
Deprecate this package

### ISSUE THREAD

**Issue by marionebl** [meandmax/patternplate-sass-transform#4]
Hey there @KarstenBuckstegge @meandmax,

I have implemented the equivalent of this transform here: https://github.com/marionebl/patternplate-transform-node-sass. To avoid confusion for users it would be super dope if you could deprecate this repository and link there.

Cheers
Mario

**Comment by karstenvds** [comment]
Done.

**Comment by marionebl** [comment]
You the best <3
